# This file is auto-generated by Terraform
# Do not edit manually - run 'terraform apply' to update

[webservers]
web-server ansible_host=${web_server_ip} ansible_user=ubuntu

[ansible_controller]
ansible-controller ansible_host=${ansible_controller_ip} ansible_user=ubuntu

[monitoring_servers]
monitoring-server ansible_host=${monitoring_server_ip} ansible_user=ubuntu

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'