# This file is auto-generated by Terraform
# Do not edit manually - run 'terraform apply' to update

[webservers]
${web_server_instance_id} ansible_connection=ssm ansible_user=ubuntu

[ansible_controller]
${ansible_controller_instance_id} ansible_connection=ssm ansible_user=ubuntu

[monitoring_servers]
${monitoring_server_instance_id} ansible_connection=ssm ansible_user=ubuntu

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ecr_repository_uri=${ecr_repository_uri}